title: "main h1, h1.page-title, h1"
publish_date: "time[datetime], .published-date, .updated-date, meta[name='date']"
breadcrumbs: ".breadcrumb li"
content_blocks:
  - "main article h2, main article h3"
  - "main article p, main article ul, main article ol, .callout, .tip"
