interest_rates:
  - DGS1MO
  - DGS3MO
  - DGS2
  - DGS10
  - DGS30
inflation:
  - CPIAUCSL   # CPI
  - CPILFESL   # Core CPI
  - PCEPI      # PCE Price Index
sector_growth:
  - INDPRO     # Industrial Production Index
  - IPMAN      # Manufacturing
  - IPUTIL     # Utilities
  - IPMINE     # Mining
